import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for 90percent.",
};

const Privacy = () => {
  return (
    <div className="mx-auto w-full max-w-3xl px-4 py-10">
      <div className="mb-10">
        <h1 className="text-3xl font-bold text-app-secondary">
          Privacy Policy
        </h1>
        <p className="mt-2 text-sm text-gray-500">Last updated: February 27, 2026</p>
      </div>

      <div className="flex flex-col gap-8 text-[15px] leading-relaxed text-gray-600">
        <p className="font-medium">
          This Privacy Policy describes our policies and procedures on the
          collection, use and disclosure of your information when you use the
          Service and tells you about your privacy rights and how the law
          protects you. We use your personal data to provide and improve the
          Service. By using the Service, you agree to the collection and use of
          information in accordance with this Privacy Policy.
        </p>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Interpretation and Definitions
          </h2>
          <h3 className="mb-2 font-semibold text-app-secondary">
            Interpretation
          </h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>
        </section>

        <section>
          <h3 className="mb-2 font-semibold text-app-secondary">Definitions</h3>
          <p className="mb-3">For the purposes of this Privacy Policy:</p>
          <ul className="ml-5 list-disc space-y-2">
            <li>
              <strong>Account</strong> means a unique account created for you to
              access our Service or parts of our Service.
            </li>
            <li>
              <strong>Company</strong> (referred to as either &quot;the
              Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
              this Agreement) refers to 90percent.
            </li>
            <li>
              <strong>Cookies</strong> are small files placed on your computer,
              mobile device or any other device by a website, containing the
              details of your browsing history on that website among its many
              uses.
            </li>
            <li>
              <strong>Country</strong> refers to Nigeria.
            </li>
            <li>
              <strong>Device</strong> means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to
              an identified or identifiable individual.
            </li>
            <li>
              <strong>Service</strong> refers to the Website.
            </li>
            <li>
              <strong>Service Provider</strong> means any natural or legal person
              who processes the data on behalf of the Company.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected automatically,
              either generated by the use of the Service or from the Service
              infrastructure itself.
            </li>
            <li>
              <strong>Website</strong> refers to 90percent, accessible from{" "}
              <a
                href="https://90percent.com"
                className="text-app-primary hover:underline"
              >
                https://90percent.com
              </a>
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Collecting and Using Your Personal Data
          </h2>
          <h3 className="mb-2 font-semibold text-app-secondary">
            Personal Data
          </h3>
          <p className="mb-3">
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you. Personally identifiable information may include, but is
            not limited to:
          </p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Usage Data</li>
          </ul>
        </section>

        <section>
          <h3 className="mb-2 font-semibold text-app-secondary">Usage Data</h3>
          <p className="mb-3">
            Usage Data is collected automatically when using the Service. Usage
            Data may include information such as your Device&apos;s Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that you visit, the time and date of your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </p>
          <p>
            When you access the Service by or through a mobile device, we may
            collect certain information automatically, including the type of
            mobile device you use, your mobile device unique ID, the IP address
            of your mobile device, your mobile operating system, the type of
            mobile Internet browser you use, unique device identifiers and other
            diagnostic data.
          </p>
        </section>

        <section>
          <h3 className="mb-2 font-semibold text-app-secondary">
            Information from Third-Party Social Media Services
          </h3>
          <p>
            The Company allows you to create an account and log in to use the
            Service through Third-party Social Media Services such as Google. If
            you decide to register through a Third-Party Social Media Service, we
            may collect personal data that is already associated with your
            Third-Party Social Media Service&apos;s account, such as your name,
            your email address, your activities or your contact list associated
            with that account.
          </p>
        </section>

        <section>
          <h3 className="mb-2 font-semibold text-app-secondary">
            Tracking Technologies and Cookies
          </h3>
          <p className="mb-3">
            We use Cookies and similar tracking technologies to track the
            activity on our Service and store certain information. The
            technologies we use may include:
          </p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>
              <strong>Browser Cookies:</strong> A cookie is a small file placed
              on your Device. You can instruct your browser to refuse all Cookies
              or to indicate when a Cookie is being sent.
            </li>
            <li>
              <strong>Web Beacons:</strong> Certain sections of our Service and
              our emails may contain small electronic files known as web beacons
              that permit the Company to count users who have visited those pages
              or opened an email.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Use of Your Personal Data
          </h2>
          <p className="mb-3">
            The Company may use Personal Data for the following purposes:
          </p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>To provide and maintain our Service</li>
            <li>To manage your Account and registration</li>
            <li>For the performance of a contract</li>
            <li>
              To contact you regarding updates or informative communications
            </li>
            <li>
              To provide you with news, special offers and general information
              about similar services
            </li>
            <li>To manage your requests</li>
            <li>For business transfers</li>
            <li>
              For data analysis, identifying usage trends, and improving the
              Service
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Sharing Your Personal Data
          </h2>
          <p className="mb-3">
            We may share your personal information in the following situations:
          </p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>
              <strong>With Service Providers:</strong> To monitor and analyze the
              use of our Service
            </li>
            <li>
              <strong>For business transfers:</strong> In connection with any
              merger, sale of Company assets, or acquisition
            </li>
            <li>
              <strong>With Affiliates:</strong> With our affiliates, who are
              required to honour this Privacy Policy
            </li>
            <li>
              <strong>With other users:</strong> When you share personal
              information or interact in public areas with other users
            </li>
            <li>
              <strong>With your consent:</strong> For any other purpose with your
              consent
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Retention of Your Personal Data
          </h2>
          <p>
            The Company will retain your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will
            retain and use your Personal Data to the extent necessary to comply
            with our legal obligations, resolve disputes, and enforce our legal
            agreements and policies.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Delete Your Personal Data
          </h2>
          <p>
            You have the right to delete or request that we assist in deleting
            the Personal Data that we have collected about you. You may update,
            amend, or delete your information at any time by signing in to your
            Account and visiting the account settings section. You may also
            contact us to request access to, correct, or delete any personal
            information that you have provided to us.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Security of Your Personal Data
          </h2>
          <p>
            The security of your Personal Data is important to us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While we strive to use
            commercially acceptable means to protect your Personal Data, we
            cannot guarantee its absolute security.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Children&apos;s Privacy
          </h2>
          <p>
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If you are a parent or guardian and you are
            aware that your child has provided us with Personal Data, please
            contact us.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Links to Other Websites
          </h2>
          <p>
            Our Service may contain links to other websites that are not operated
            by us. We strongly advise you to review the Privacy Policy of every
            site you visit. We have no control over and assume no responsibility
            for the content, privacy policies or practices of any third party
            sites or services.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Changes to this Privacy Policy
          </h2>
          <p>
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page and
            updating the &quot;Last updated&quot; date. You are advised to review
            this Privacy Policy periodically for any changes.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Contact Us
          </h2>
          <p>
            If you have any questions about this Privacy Policy, you can contact
            us by email:{" "}
            <a
              href="mailto:passpadi.com@gmail.com"
              className="font-medium text-app-primary hover:underline"
            >
              passpadi.com@gmail.com
            </a>
          </p>
        </section>
      </div>
    </div>
  );
};

export default Privacy;
