import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for 90percent.",
};

const Privacy = () => {
  return (
    <div className="mx-auto w-full max-w-3xl px-4 py-10">
      <div className="mb-10">
        <h1 className="text-3xl font-bold text-app-secondary">
          Privacy Policy
        </h1>
        <p className="mt-2 text-sm text-gray-500">Last updated: March 1, 2026</p>
      </div>

      <div className="flex flex-col gap-8 text-[15px] leading-relaxed text-gray-600">
        <p className="font-medium">
          This Privacy Policy describes our policies and procedures on the
          collection, use and disclosure of your information when you use the
          Service and tells you about your privacy rights and how the law
          protects you. We use your personal data to provide and improve the
          Service. By using the Service, you agree to the collection and use of
          information in accordance with this Privacy Policy.
        </p>

        {/* ── Definitions ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Interpretation and Definitions
          </h2>
          <h3 className="mb-2 font-semibold text-app-secondary">
            Interpretation
          </h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>
        </section>

        <section>
          <h3 className="mb-2 font-semibold text-app-secondary">Definitions</h3>
          <p className="mb-3">For the purposes of this Privacy Policy:</p>
          <ul className="ml-5 list-disc space-y-2">
            <li>
              <strong>Account</strong> means a unique account created for you to
              access our Service or parts of our Service.
            </li>
            <li>
              <strong>Application</strong> refers to 90percent, the software
              program provided by the Company, available for download on mobile
              devices through the Apple App Store, Google Play Store, or
              accessible via the Website.
            </li>
            <li>
              <strong>Company</strong> (referred to as either &quot;the
              Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
              this Agreement) refers to 90percent LTD.
            </li>
            <li>
              <strong>Cookies</strong> are small files placed on your computer,
              mobile device or any other device by a website, containing the
              details of your browsing history on that website among its many
              uses.
            </li>
            <li>
              <strong>Country</strong> refers to Nigeria.
            </li>
            <li>
              <strong>Device</strong> means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to
              an identified or identifiable individual.
            </li>
            <li>
              <strong>Service</strong> refers to the Application and/or the
              Website, individually or collectively.
            </li>
            <li>
              <strong>Service Provider</strong> means any natural or legal person
              who processes the data on behalf of the Company.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected automatically,
              either generated by the use of the Service or from the Service
              infrastructure itself.
            </li>
            <li>
              <strong>Website</strong> refers to 90percent, accessible from{" "}
              <a
                href="https://90percent.app"
                className="text-app-primary hover:underline"
              >
                https://90percent.app
              </a>
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service.
            </li>
          </ul>
        </section>

        {/* ── Data Collection ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Collecting and Using Your Personal Data
          </h2>
          <h3 className="mb-2 font-semibold text-app-secondary">
            Personal Data
          </h3>
          <p className="mb-3">
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you. Personally identifiable information may include, but is
            not limited to:
          </p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Profile photo (if provided)</li>
            <li>Usage Data</li>
          </ul>
        </section>

        <section>
          <h3 className="mb-2 font-semibold text-app-secondary">Usage Data</h3>
          <p className="mb-3">
            Usage Data is collected automatically when using the Service. Usage
            Data may include information such as your Device&apos;s Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that you visit, the time and date of your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </p>
          <p>
            When you access the Service by or through a mobile device, we may
            collect certain information automatically, including the type of
            mobile device you use, your mobile device unique ID, the IP address
            of your mobile device, your mobile operating system, the type of
            mobile Internet browser you use, unique device identifiers and other
            diagnostic data.
          </p>
        </section>

        {/* ── Mobile App Data ── */}
        <section>
          <h3 className="mb-2 font-semibold text-app-secondary">
            Information Collected While Using the Application
          </h3>
          <p className="mb-3">
            While using our Application, in order to provide features of our
            Application, we may collect, with your prior permission:
          </p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>
              <strong>Device identifiers</strong> such as your advertising ID
              (IDFA on iOS, GAID on Android), device model, operating system
              version, and app version.
            </li>
            <li>
              <strong>Push notification token</strong> to send you study
              reminders, event notifications, and other updates. You may opt out
              at any time through your device settings.
            </li>
            <li>
              <strong>Study activity data</strong> including questions answered,
              scores, time spent studying, and subjects selected.
            </li>
          </ul>
          <p className="mt-3">
            We use this information to provide and improve features of the
            Service, personalise your experience, and deliver relevant content.
            You can enable or disable access to this information at any time
            through your Device settings.
          </p>
        </section>

        {/* ── Third-Party Social Login ── */}
        <section>
          <h3 className="mb-2 font-semibold text-app-secondary">
            Information from Third-Party Social Media Services
          </h3>
          <p>
            The Company allows you to create an account and log in to use the
            Service through Third-party Social Media Services such as Google. If
            you decide to register through or grant us access to a Third-Party
            Social Media Service, we may collect personal data that is already
            associated with your Third-Party Social Media Service&apos;s
            account, such as your name, your email address, and your profile
            picture associated with that account. This data is used solely to
            create and manage your 90percent account.
          </p>
        </section>

        {/* ── Cookies & Tracking ── */}
        <section>
          <h3 className="mb-2 font-semibold text-app-secondary">
            Tracking Technologies and Cookies
          </h3>
          <p className="mb-3">
            We use Cookies and similar tracking technologies to track the
            activity on our Service and store certain information. The
            technologies we use may include:
          </p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>
              <strong>Browser Cookies:</strong> A cookie is a small file placed
              on your Device. You can instruct your browser to refuse all Cookies
              or to indicate when a Cookie is being sent.
            </li>
            <li>
              <strong>Web Beacons:</strong> Certain sections of our Service and
              our emails may contain small electronic files known as web beacons
              that permit the Company to count users who have visited those pages
              or opened an email.
            </li>
            <li>
              <strong>Local Storage:</strong> We may use local storage
              technologies (such as HTML5) to store user preferences and
              session information.
            </li>
          </ul>
        </section>

        {/* ── Advertising ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Advertising
          </h2>
          <p className="mb-3">
            We may use third-party advertising companies to serve ads when you
            visit our Service. These companies may use information about your
            visits to our Website and other websites and applications (not
            including your name, address, email address, or telephone number) in
            order to provide advertisements about goods and services of interest
            to you.
          </p>

          <h3 className="mb-2 font-semibold text-app-secondary">
            Google AdSense &amp; DoubleClick Cookie
          </h3>
          <p className="mb-3">
            Google, as a third-party vendor, uses cookies to serve ads on our
            Service. Google&apos;s use of the DART cookie enables it to serve ads
            to our users based on previous visits to our Service and other
            websites. You may opt out of the use of the DART cookie by visiting
            the{" "}
            <a
              href="https://policies.google.com/technologies/ads"
              target="_blank"
              rel="noopener noreferrer"
              className="text-app-primary hover:underline"
            >
              Google ad and content network privacy policy
            </a>
            .
          </p>

          <h3 className="mb-2 font-semibold text-app-secondary">
            Google AdMob (Mobile Advertising)
          </h3>
          <p className="mb-3">
            Our mobile Application may use Google AdMob to serve advertisements.
            AdMob may collect and use data including your device&apos;s
            advertising identifier, IP address, and usage data to deliver
            personalised ads. You can opt out of personalised advertising by
            adjusting your device settings:
          </p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>
              <strong>iOS:</strong> Settings &gt; Privacy &amp; Security &gt;
              Tracking, and disable &quot;Allow Apps to Request to Track&quot;.
            </li>
            <li>
              <strong>Android:</strong> Settings &gt; Google &gt; Ads, and enable
              &quot;Opt out of Ads Personalisation&quot;.
            </li>
          </ul>
          <p className="mt-3">
            For more information on how Google uses your data, please visit{" "}
            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-app-primary hover:underline"
            >
              Google&apos;s Privacy Policy
            </a>
            .
          </p>
        </section>

        {/* ── Use of Data ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Use of Your Personal Data
          </h2>
          <p className="mb-3">
            The Company may use Personal Data for the following purposes:
          </p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>To provide and maintain our Service</li>
            <li>To manage your Account and registration</li>
            <li>For the performance of a contract</li>
            <li>
              To contact you regarding updates or informative communications
            </li>
            <li>
              To provide you with news, special offers and general information
              about similar services
            </li>
            <li>To manage your requests</li>
            <li>For business transfers</li>
            <li>
              For data analysis, identifying usage trends, and improving the
              Service
            </li>
            <li>
              To deliver targeted advertising and measure its effectiveness
            </li>
          </ul>
        </section>

        {/* ── Sharing ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Sharing Your Personal Data
          </h2>
          <p className="mb-3">
            We may share your personal information in the following situations:
          </p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>
              <strong>With Service Providers:</strong> To monitor and analyze the
              use of our Service
            </li>
            <li>
              <strong>With advertising partners:</strong> We may share
              information with third-party advertising partners (including Google
              AdSense and AdMob) to deliver and measure advertising on the
              Service
            </li>
            <li>
              <strong>For business transfers:</strong> In connection with any
              merger, sale of Company assets, or acquisition
            </li>
            <li>
              <strong>With Affiliates:</strong> With our affiliates, who are
              required to honour this Privacy Policy
            </li>
            <li>
              <strong>With other users:</strong> When you share personal
              information or interact in public areas with other users
            </li>
            <li>
              <strong>With your consent:</strong> For any other purpose with your
              consent
            </li>
          </ul>
        </section>

        {/* ── Retention ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Retention of Your Personal Data
          </h2>
          <p>
            The Company will retain your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will
            retain and use your Personal Data to the extent necessary to comply
            with our legal obligations, resolve disputes, and enforce our legal
            agreements and policies.
          </p>
        </section>

        {/* ── Deletion ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Delete Your Personal Data
          </h2>
          <p className="mb-3">
            You have the right to delete or request that we assist in deleting
            the Personal Data that we have collected about you.
          </p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>
              <strong>In-app:</strong> Sign in to your Account, go to Profile
              &gt; Settings, and select &quot;Delete Account&quot;. Your account
              and associated data will be permanently removed within 30 days.
            </li>
            <li>
              <strong>By email:</strong> Contact us at{" "}
              <a
                href="mailto:passpadi.com@gmail.com"
                className="text-app-primary hover:underline"
              >
                passpadi.com@gmail.com
              </a>{" "}
              with a deletion request. We will process your request within 30
              days.
            </li>
          </ul>
          <p className="mt-3">
            Please note that we may need to retain certain information to comply
            with legal obligations or to resolve disputes.
          </p>
        </section>

        {/* ── Security ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Security of Your Personal Data
          </h2>
          <p>
            The security of your Personal Data is important to us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While we strive to use
            commercially acceptable means to protect your Personal Data, we
            cannot guarantee its absolute security.
          </p>
        </section>

        {/* ── Children ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Children&apos;s Privacy
          </h2>
          <p>
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If you are a parent or guardian and you are
            aware that your child has provided us with Personal Data, please
            contact us. If we become aware that we have collected Personal Data
            from anyone under the age of 13 without verification of parental
            consent, we take steps to remove that information from our servers.
          </p>
        </section>

        {/* ── GDPR / International ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Your Rights Under Data Protection Laws
          </h2>
          <p className="mb-3">
            Depending on your location, you may have certain rights regarding
            your Personal Data, including:
          </p>
          <ul className="ml-5 list-disc space-y-1.5">
            <li>
              <strong>Right of access:</strong> You can request copies of your
              Personal Data.
            </li>
            <li>
              <strong>Right to rectification:</strong> You can ask us to correct
              inaccurate or incomplete information.
            </li>
            <li>
              <strong>Right to erasure:</strong> You can ask us to delete your
              Personal Data.
            </li>
            <li>
              <strong>Right to restrict processing:</strong> You can ask us to
              limit how we use your data.
            </li>
            <li>
              <strong>Right to data portability:</strong> You can request a copy
              of your data in a machine-readable format.
            </li>
            <li>
              <strong>Right to object:</strong> You can object to our processing
              of your Personal Data.
            </li>
            <li>
              <strong>Right to withdraw consent:</strong> Where processing is
              based on consent, you may withdraw it at any time.
            </li>
          </ul>
          <p className="mt-3">
            To exercise any of these rights, please contact us at{" "}
            <a
              href="mailto:passpadi.com@gmail.com"
              className="text-app-primary hover:underline"
            >
              passpadi.com@gmail.com
            </a>
            . We will respond to your request within 30 days.
          </p>
        </section>

        {/* ── External Links ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Links to Other Websites
          </h2>
          <p>
            Our Service may contain links to other websites that are not operated
            by us. We strongly advise you to review the Privacy Policy of every
            site you visit. We have no control over and assume no responsibility
            for the content, privacy policies or practices of any third party
            sites or services.
          </p>
        </section>

        {/* ── Changes ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Changes to this Privacy Policy
          </h2>
          <p>
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page and
            updating the &quot;Last updated&quot; date. You are advised to review
            this Privacy Policy periodically for any changes.
          </p>
        </section>

        {/* ── Contact ── */}
        <section>
          <h2 className="mb-3 text-lg font-semibold text-app-secondary">
            Contact Us
          </h2>
          <p>
            If you have any questions about this Privacy Policy, you can contact
            us by email:{" "}
            <a
              href="mailto:passpadi.com@gmail.com"
              className="font-medium text-app-primary hover:underline"
            >
              passpadi.com@gmail.com
            </a>
          </p>
        </section>
      </div>
    </div>
  );
};

export default Privacy;
